.\" Pipe this output to groff -m man -K utf8 -T utf8 | less -R
.\"
.mso an.tmac
.TH "DUNE-CACHE" 1 "" "Dune 3.5.0" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'cache \N'45' Manage the shared cache of build artifacts
.SH SYNOPSIS
.P
\fBdune cache\fR [\fB\N'45'\N'45'size\fR=\fIBYTES\fR] [\fB\N'45'\N'45'trimmed\N'45'size\fR=\fIBYTES\fR] [\fIOPTION\fR]… [\fIACTION\fR]
.SH DESCRIPTION
.P
Dune can share build artifacts between workspaces\N'46' Currently, the only action supported by this command is `trim`, but we plan to provide more functionality soon\N'46' 
.SH ACTIONS
.P
\fBtrim\fR trim the shared cache to free space\N'46'
.SH ARGUMENTS
.TP 4
\fIACTION\fR
The cache action to perform (\fBtrim\fR)
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'size\fR=\fIBYTES\fR
size to trim the cache to
.TP 4
\fB\N'45'\N'45'trimmed\N'45'size\fR=\fIBYTES\fR
size to trim from the cache
.SH COMMON OPTIONS
.P
These options are common to all commands\N'46'
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=\fBauto\fR)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of \fBauto\fR, \fBpager\fR, \fBgroff\fR or \fBplain\fR\N'46' With \fBauto\fR, the format is \fBpager\fR or \fBplain\fR whenever the \fBTERM\fR env var is \fBdumb\fR or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH MORE HELP
.P
Use `\fBdune\fR \fICOMMAND\fR \N'45'\N'45'help\N'39' for help on a single command\N'46'
.SH EXIT STATUS
.P
\fBcache\fR exits with the following status:
.TP 4
0
on success\N'46'
.TP 4
123
on indiscriminate errors reported on standard error\N'46'
.TP 4
124
on command line parsing errors\N'46'
.TP 4
125
on unexpected internal errors (bugs)\N'46'
.SH BUGS
.P
Check bug reports at https://github\N'46'com/ocaml/dune/issues
.SH SEE ALSO
.P
dune(1)