(* generated by dune *)

(** @canonical Ptranal.Golf *)
module Golf = Ptranal__Golf

(** @canonical Ptranal.Olf *)
module Olf = Ptranal__Olf

(** @canonical Ptranal.Setp *)
module Setp = Ptranal__Setp

(** @canonical Ptranal.Steensgaard *)
module Steensgaard = Ptranal__Steensgaard

(** @canonical Ptranal.Uref *)
module Uref = Ptranal__Uref

module Ptranal__ = struct end
[@@deprecated "this module is shadowed"]
