(* generated by dune *)

(** @canonical TianshuCil.Alpha *)
module Alpha = TianshuCil__Alpha

(** @canonical TianshuCil.Bitmap *)
module Bitmap = TianshuCil__Bitmap

(** @canonical TianshuCil.Cabs *)
module Cabs = TianshuCil__Cabs

(** @canonical TianshuCil.Cabs2cil *)
module Cabs2cil = TianshuCil__Cabs2cil

(** @canonical TianshuCil.Cabshelper *)
module Cabshelper = TianshuCil__Cabshelper

(** @canonical TianshuCil.Cabsvisit *)
module Cabsvisit = TianshuCil__Cabsvisit

(** @canonical TianshuCil.Cfg *)
module Cfg = TianshuCil__Cfg

(** @canonical TianshuCil.Check *)
module Check = TianshuCil__Check

(** @canonical TianshuCil.Cil *)
module Cil = TianshuCil__Cil

(** @canonical TianshuCil.Cilint *)
module Cilint = TianshuCil__Cilint

(** @canonical TianshuCil.Cillower *)
module Cillower = TianshuCil__Cillower

(** @canonical TianshuCil.Ciltools *)
module Ciltools = TianshuCil__Ciltools

(** @canonical TianshuCil.Cilutil *)
module Cilutil = TianshuCil__Cilutil

(** @canonical TianshuCil.Cilversion *)
module Cilversion = TianshuCil__Cilversion

(** @canonical TianshuCil.Clexer *)
module Clexer = TianshuCil__Clexer

(** @canonical TianshuCil.Clist *)
module Clist = TianshuCil__Clist

(** @canonical TianshuCil.Cparser *)
module Cparser = TianshuCil__Cparser

(** @canonical TianshuCil.Cprint *)
module Cprint = TianshuCil__Cprint

(** @canonical TianshuCil.Dataflow *)
module Dataflow = TianshuCil__Dataflow

(** @canonical TianshuCil.Dominators *)
module Dominators = TianshuCil__Dominators

(** @canonical TianshuCil.Errormsg *)
module Errormsg = TianshuCil__Errormsg

(** @canonical TianshuCil.Escape *)
module Escape = TianshuCil__Escape

(** @canonical TianshuCil.Expcompare *)
module Expcompare = TianshuCil__Expcompare

(** @canonical TianshuCil.Feature *)
module Feature = TianshuCil__Feature

(** @canonical TianshuCil.Formatcil *)
module Formatcil = TianshuCil__Formatcil

(** @canonical TianshuCil.Formatlex *)
module Formatlex = TianshuCil__Formatlex

(** @canonical TianshuCil.Formatparse *)
module Formatparse = TianshuCil__Formatparse

(** @canonical TianshuCil.Frontc *)
module Frontc = TianshuCil__Frontc

(** @canonical TianshuCil.GrowArray *)
module GrowArray = TianshuCil__GrowArray

(** @canonical TianshuCil.Inthash *)
module Inthash = TianshuCil__Inthash

(** @canonical TianshuCil.Lexerhack *)
module Lexerhack = TianshuCil__Lexerhack

(** @canonical TianshuCil.Libmaincil *)
module Libmaincil = TianshuCil__Libmaincil

(** @canonical TianshuCil.Longarray *)
module Longarray = TianshuCil__Longarray

(** @canonical TianshuCil.Machdep *)
module Machdep = TianshuCil__Machdep

(** @canonical TianshuCil.Machdepenv *)
module Machdepenv = TianshuCil__Machdepenv

(** @canonical TianshuCil.Mergecil *)
module Mergecil = TianshuCil__Mergecil

(** @canonical TianshuCil.Patch *)
module Patch = TianshuCil__Patch

(** @canonical TianshuCil.Pretty *)
module Pretty = TianshuCil__Pretty

(** @canonical TianshuCil.Rmtmps *)
module Rmtmps = TianshuCil__Rmtmps

(** @canonical TianshuCil.Stats *)
module Stats = TianshuCil__Stats

(** @canonical TianshuCil.Trace *)
module Trace = TianshuCil__Trace

(** @canonical TianshuCil.Util *)
module Util = TianshuCil__Util

(** @canonical TianshuCil.Whitetrack *)
module Whitetrack = TianshuCil__Whitetrack

module TianshuCil__ = struct end
[@@deprecated "this module is shadowed"]
