(* generated by dune *)

(** @canonical Llvm.Llvmgen *)
module Llvmgen = Llvm__Llvmgen

(** @canonical Llvm.Llvmssa *)
module Llvmssa = Llvm__Llvmssa

(** @canonical Llvm.Llvmutils *)
module Llvmutils = Llvm__Llvmutils

module Llvm__ = struct end
[@@deprecated "this module is shadowed"]
